#!/usr/bin/env bash
#
# Build the GitHub Pages landing page (index.html) and refresh the README's
# "Edições" list from whatever editions exist under releases/. Run it after
# rendering a new edition, then commit & push so it goes live.
#
#   scripts/publish.sh
#
set -euo pipefail

cd "$(dirname "$0")/.."
command -v jq >/dev/null || { echo "This script needs 'jq' installed."; exit 1; }

BASE_URL="https://boaglio.github.io/boteco-das-ias"

# Collect editions (dirs named YYYY-MM-DD that have a magazine.html), newest first.
editions=()
for d in $(ls -1 releases 2>/dev/null | sort -r); do
    [ -f "releases/$d/magazine.html" ] && editions+=("$d")
done

# --- index.html (Pages landing) ------------------------------------------------
{
cat <<'HTML'
<!DOCTYPE html>
<html lang="pt-br">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Boteco das IAs</title>
<style>
:root{--bg:#faf7f2;--ink:#2b2b2b;--accent:#c0392b}
body{margin:0;background:var(--bg);color:var(--ink);font-family:system-ui,sans-serif;line-height:1.5}
header{text-align:center;padding:2.5rem 1rem 1.5rem;border-bottom:3px solid var(--accent)}
header img{width:160px;border-radius:16px}
header h1{margin:.6rem 0 .2rem;font-size:2rem}
header p{margin:0;color:#777}
main{max-width:640px;margin:0 auto;padding:1.5rem 1rem}
ul{list-style:none;margin:0;padding:0}
li{padding:.9rem 1rem;border:1px solid #e2dccf;border-radius:12px;background:#fff;margin-bottom:.7rem}
li a.edition{font-weight:700;color:var(--ink);text-decoration:none;font-size:1.1rem}
li a.edition:hover{color:var(--accent)}
.links{margin-top:.3rem;font-size:.85rem}
.links a{color:var(--accent);text-decoration:none;margin-right:.8rem}
footer{text-align:center;color:#999;font-size:.8rem;padding:2rem 1rem}
</style>
</head>
<body>
<header>
<img src="assets/logo.png" alt="Boteco das IAs">
<h1>Boteco das IAs</h1>
<p>Boletim semanal de notícias de tecnologia, comentadas por IAs.</p>
</header>
<main>
<ul>
HTML

if [ ${#editions[@]} -eq 0 ]; then
    echo '<li>Nenhuma edição ainda.</li>'
else
    for d in "${editions[@]}"; do
        title=$(jq -r '.title // "Boteco das IAs"' "releases/$d/magazine.json" 2>/dev/null)
        pdf=""; [ -f "releases/$d/magazine.pdf" ] && pdf="<a href=\"releases/$d/magazine.pdf\">PDF</a>"
        li=""; [ -d "releases/$d/linkedin" ] && li="<a href=\"releases/$d/linkedin/\">LinkedIn</a>"
        printf '<li><a class="edition" href="releases/%s/magazine.html">%s</a><div class="links">%s %s</div></li>\n' \
            "$d" "$title" "$pdf" "$li"
    done
fi

cat <<'HTML'
</ul>
</main>
<footer>github.com/boaglio/boteco-das-ias</footer>
</body>
</html>
HTML
} > index.html
echo "Wrote index.html (${#editions[@]} edition(s))"

# --- README "Edições" section --------------------------------------------------
md=$(mktemp)
{
    echo "<!-- EDITIONS:START (generated by scripts/publish.sh) -->"
    if [ ${#editions[@]} -eq 0 ]; then
        echo "_Nenhuma edição publicada ainda._"
    else
        for d in "${editions[@]}"; do
            title=$(jq -r '.title // "Boteco das IAs"' "releases/$d/magazine.json" 2>/dev/null)
            echo "- **$d** — [$title]($BASE_URL/releases/$d/magazine.html)"
        done
    fi
    echo "<!-- EDITIONS:END -->"
} > "$md"

# Replace the marked block in README.md.
python3 - "$md" <<'PY'
import re, sys, pathlib
block = pathlib.Path(sys.argv[1]).read_text()
readme = pathlib.Path("README.md")
text = readme.read_text()
new = re.sub(r"<!-- EDITIONS:START.*?EDITIONS:END -->", block.strip(), text, flags=re.S)
readme.write_text(new)
PY
rm -f "$md"
echo "Updated README.md editions list"
